version: "3.8"
services:
  api:
    container_name: go-boilerplate-api
    restart: unless-stopped
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "${APP_PUBLIC_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    networks:
      - postgres

  postgres:
    container_name: go-boilerplate-postgres
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - postgres

  pgadmin:
    container_name: go-boilerplate-pgadmin
    restart: unless-stopped
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: